# Generated by Django 5.1.2 on 2024-10-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaurabapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedetail',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='savedetail',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
